# Generated by Django 4.0.2 on 2022-02-28 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 15, 50, 802539)),
        ),
    ]
