# Generated by Django 4.0.3 on 2022-03-01 09:44

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_order_id_alter_orders_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=uuid.UUID('6766ef79-1df5-486b-bb95-30a65bcbc357'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 15, 14, 46, 323570)),
        ),
    ]
