# Generated by Django 4.0.3 on 2022-03-01 11:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orders_order_id_alter_orders_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=uuid.UUID('8c921891-03c0-4a6f-9989-f0b78216b3e5'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 17, 28, 26, 803087)),
        ),
    ]
